# Learn Today

## assertThat()
테스트 코드를 작성할 때 사용했던 메소드이다. 이 메소드는 테스트 코드를 작성할 때 System.out.println()로 매번 출력해야하는 어려움을 줄여주기위해 종종 사용한다.  

assertThat() 메소드를 사용하기 위해서는 AssertJ 라이브러리를 import해주어야 하는데 AssertJ는 자바 JUnit의 테스트 코드에 사용되는 라이브러리로 JUnit에서 제공하는 메소드보다 좀 더 직관적이고 읽기 쉽다.


```java
import static org.assertj.core.api.Assertions.assertThat;
```
나는 실습에서 위의 구문을 통해 import해주었다. 

```java
@Test
void subtracttionTest() {
    int result = Calculator.calculate(1, "-", 2);
    assertThat(result).isEqualTo(-1);
}
```
위와 같은 포맷으로 assertThat()을 사용하였다.

## assertThatCode()와 assertThatThrownBy()

```java
@DisplayName("나눗셈에서 0을 나누는 경우 IllegalArgument 예외를 발생시킨다.")
    @Test
    void calculateExceptionTest() {
        assertThatCode(() -> Calculator.calculate(new PositiveNumber(10), "/", new PositiveNumber(0)))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("0으로는 나눌 수 없습니다.");
    }
```
위의 코드는 내가 실습할 때 사용했던 코드이다. 코드를 살펴보면 assertThatCode를 통해 Calculator.caculate() 메소드가 0으로 나누었을 때 예외를 발생하는지 예외가 발생했다면 메시지가 "0으로는 나눌 수 없습니다."인지 테스트하는 코드였다.

assertThatCode() 메소드를 검색해봤을 때 assertThatThrownBy() 메소드와 비교하는 경우가 많아서 나도 찾아보았다. 

결론부터 말하자면

    assertThatCode() 메소드는 예외가 던져지지 않아도 실패하지 않는 반면 assertThatThrownBy() 메소드는 예외가 던져지지 않으면 바로 실패한다. 

따라서 assertThatCode()는 해당 코드 부분에서 예외가 발생했을 때 예외처리도 잘 처리하나 테스트해볼 때 사용하고, assertThatThrownBy()는 예외를 무조건 던져야하는 상황을 테스트해볼 때 사용한다고 보면 된다.